@base=http://localhost:8080
@admin_token=f559c7d6-2f5a-4220-806a-83e23c4e91c3
@namespace=default
@key=qifYRkw0B47FFhNN


POST {{base}}/create/{{namespace}}/{{key}}


>{%
    client.global.set("admin_token", response.body.admin_key);
%}

###
GET {{base}}/info/{{key}}

###
GET {{base}}/hit/{{namespace}}/{{key}}


#{{base}}/info/jasoncameron.dev/portfolio



POST {{base}}/delete/jasoncameron.dev/portfolio
Authorization: Bearer {{token}}




//
###
POST {{base}}/reset/{{namespace}}/{{key}}?token={{admin_token}}

###
POST {{base}}/update/{{namespace}}/{{key}}?token={{admin_token}}&value=40589

###
// use at the end to clear up testcases.
POST {{base}}/delete/{{key}}?token={{admin_token}}
