@base=http://localhost:8080
@token="REPLACE_ME"
@key=jvc


POST {{base}}/delete/{{key}}?token=e7fad266-b34f-4fc3-8788-a6f78f71af1c

#GET http://localhost:8080/info/jasoncameron.dev/portfolio


#{{base}}/info/jasoncameron.dev/portfolio



POST {{base}}/delete/jasoncameron.dev/portfolio
Authorization: Bearer {{token}}




//
###
PUT http://localhost:8080/update/SAOH9hhi220cn4VJ/qifYRkw0B47FFhNN?value=4978&token=d7c38748-7f94-4ae1-adc3-fa3bbc22b6e0
